title: Embracing Authenticity
description: A space to grow, reflect, and be your true self.

url: "https://embracingauthenticity.co.uk"
baseurl: "" # Keep empty if not in a subdirectory

markdown: kramdown
permalink: /blog/:title/
future: true

# ✅ Plugins - Clean and Correct
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate-v2

# ✅ Pagination Settings (jekyll-paginate-v2)
pagination:
  enabled: true
  per_page: 12
  permalink: /blog/page/:num/
  title: ":title - Page :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true

# ✅ Collections
collections:
  tag:
    output: true
    permalink: /tag/:name/
  music_music:
    output: true
    permalink: /music-therapy/:title/
    sort_by: date
    sort_order: descending
  pages:
    output: true
    permalink: /:name/

# ✅ Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      tags: []

  - scope:
      path: ""
      type: music_music
    values:
      layout: music
      tags: []
      sitemap: true

# ✅ Add optional image fallback for social previews
image: /images/default-social.jpg
